[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EasonDrone"
authors = [{name = "Eason Hua", email = "12010508@mail.sustech.edu.cn"}]
dynamic = ["version", "description"]
